server:
  port: 52001
  servlet:
    context-path: /
http:
  cors:
    allow:
      credentials: true
      headers: app Origin, Content-Type, Accept, Authorization, Access-Control-Request-Headers
      methods: GET, POST, PUT, DELETE, OPTIONS, HEAD, PATCH
      origin: http://localhost:4200
    max:
      age: 3600
    expose:
      headers:
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: student book api
  main:
    allow-bean-definition-overriding: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate.default_schema: public
      hibernate.format_sql: true
      hibernate.jdbc.time_zone: UTC
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/TP1
    username: root
    password: teyadidi
